import com.comsol.model.*;
import com.comsol.model.util.*;
import java.io.*;
import java.util.*;

public class Dia60Al40_ComsolRouteB_Skeleton {
    static class Ptc { String shape; double x,y,r; int type; }
    static void P(String s){ System.err.println(s); }
    Model m; ArrayList<Ptc> pts = new ArrayList<Ptc>(); String csvPath; String outPath;
    public static void main(String[] args) throws Exception {
        System.err.println("[TOOLKIT READ] OK");
        Dia60Al40_ComsolRouteB_Skeleton app = new Dia60Al40_ComsolRouteB_Skeleton();
        app.csvPath = args.length>0 ? args[0] : "D:\\CodexProjects\\scripts\\comsol_particles.csv";
        app.outPath = args.length>1 ? args[1] : "D:\\CodexProjects\\scripts\\Dia60Al40_RouteB_FromDEM.mph";
        app.build();
    }
    void build() throws Exception { readCsv(csvPath); m=ModelUtil.create("Model"); m.modelPath("D:\\CodexProjects\\scripts"); m.component().create("comp1", true); m.component("comp1").geom().create("geom1",2); m.component("comp1").geom("geom1").lengthUnit("um"); p1(); p2(); p3(); p4(); p5(); p6(); p7(); p8(); runSolve(); p9(); save(); }
    void readCsv(String path) throws Exception { P("[CSV] reading "+path); BufferedReader br=new BufferedReader(new FileReader(path)); String header=br.readLine(); if(header==null) throw new RuntimeException("empty csv"); String[] h=header.split(","); Map<String,Integer> idx=new HashMap<String,Integer>(); for(int i=0;i<h.length;i++) idx.put(h[i].trim(),i); String line; while((line=br.readLine())!=null){ if(line.trim().isEmpty()) continue; String[] a=line.split(","); Ptc p=new Ptc(); p.type=Integer.parseInt(a[idx.get("type")].trim()); p.shape=a[idx.get("shape")].trim(); p.x=Double.parseDouble(a[idx.get("x_um")].trim()); p.y=Double.parseDouble(a[idx.get("y_um")].trim()); p.r=Double.parseDouble(a[idx.get("r_um")].trim()); pts.add(p);} br.close(); P("[CSV] particles="+pts.size()); }
    void p1(){ P("[1] Parameters"); m.param().set("uTop","30[um]"); m.param().set("W_geom","400[um]"); m.param().set("E_Al","62.59[GPa]"); m.param().set("nu_Al","0.33"); m.param().set("rho_Al","2700[kg/m^3]"); m.param().set("sigy_Al","80[MPa]"); m.param().set("E_Dia","1000[GPa]"); m.param().set("nu_Dia","0.10"); m.param().set("rho_Dia","3520[kg/m^3]"); m.param().set("E_tool","600[GPa]"); m.param().set("nu_tool","0.31"); m.param().set("rho_tool","15700[kg/m^3]"); m.param().set("E_wall","15[GPa]"); m.param().set("nu_wall","0.20"); m.param().set("rho_wall","7800[kg/m^3]"); m.param().set("mu_contact","0.05"); }
    void p2(){ P("[2] Geometry"); addRect("left_wall",-20,0,20,220); addRect("right_wall",400,0,20,220); addRect("bottom",0,-18,400,18); addRect("top",0,220,400,18); int ia=0,id=0; for(Ptc p:pts){ if(p.shape.equalsIgnoreCase("Al")) addCircle("A"+(++ia),p.x,p.y,p.r); else addOct((p.shape.equalsIgnoreCase("DL")?"DL":"DS")+(++id),p.x,p.y,p.r); } m.component("comp1").geom("geom1").feature("fin").set("action","assembly"); try{m.component("comp1").geom("geom1").feature("fin").set("createpairs",true);}catch(Throwable e){} m.component("comp1").geom("geom1").run("fin"); P("  domains="+m.component("comp1").geom("geom1").getNDomains()); }
    void addRect(String t,double x,double y,double w,double h){String tag="r_"+t; m.component("comp1").geom("geom1").create(tag,"Rectangle"); m.component("comp1").geom("geom1").feature(tag).set("size",new String[]{w+"[um]",h+"[um]"}); m.component("comp1").geom("geom1").feature(tag).set("pos",new String[]{x+"[um]",y+"[um]"}); m.component("comp1").geom("geom1").feature(tag).set("selresult",true);} 
    void addCircle(String t,double x,double y,double r){String tag="c_"+t; m.component("comp1").geom("geom1").create(tag,"Circle"); m.component("comp1").geom("geom1").feature(tag).set("pos",new String[]{x+"[um]",y+"[um]"}); m.component("comp1").geom("geom1").feature(tag).set("r",r+"[um]"); m.component("comp1").geom("geom1").feature(tag).set("selresult",true);} 
    void addOct(String t,double x,double y,double R){String tag="p_"+t; m.component("comp1").geom("geom1").create(tag,"Polygon"); StringBuilder xs=new StringBuilder(),ys=new StringBuilder(); for(int k=0;k<8;k++){double a=Math.toRadians(22.5+45*k); if(k>0){xs.append(" ");ys.append(" ");} xs.append(String.format(java.util.Locale.US,"%.6f[um]",x+R*Math.cos(a))); ys.append(String.format(java.util.Locale.US,"%.6f[um]",y+R*Math.sin(a)));} m.component("comp1").geom("geom1").feature(tag).set("x",xs.toString()); m.component("comp1").geom("geom1").feature(tag).set("y",ys.toString()); m.component("comp1").geom("geom1").feature(tag).set("selresult",true);} 
    void p3(){ P("[3] Selections"); box("sel_left_wall",2,-21,1,-1,221); box("sel_right_wall",2,399,421,-1,221); box("sel_lower_punch",2,-1,401,-19,1); box("sel_upper_punch",2,-1,401,219,239); union("sel_tools",2,new String[]{"sel_lower_punch","sel_upper_punch"}); union("sel_walls",2,new String[]{"sel_left_wall","sel_right_wall"}); ArrayList<String> al=new ArrayList<String>(),dia=new ArrayList<String>(); int i=0; for(Ptc p:pts){String s="bx_p"+(++i); box(s,2,p.x-p.r-0.8,p.x+p.r+0.8,p.y-p.r-0.8,p.y+p.r+0.8); if(p.shape.equalsIgnoreCase("Al")) al.add(s); else dia.add(s);} union("sel_al",2,al.toArray(new String[0])); union("sel_dia",2,dia.toArray(new String[0])); union("sel_particles",2,new String[]{"sel_al","sel_dia"}); box("bnd_upper_inner",1,0,400,219,221); box("bnd_lower_inner",1,0,400,-1,1); }
    void box(String name,int dim,double xmin,double xmax,double ymin,double ymax){m.component("comp1").selection().create(name,"Box");m.component("comp1").selection(name).set("entitydim",dim);m.component("comp1").selection(name).set("xmin",xmin+"[um]");m.component("comp1").selection(name).set("xmax",xmax+"[um]");m.component("comp1").selection(name).set("ymin",ymin+"[um]");m.component("comp1").selection(name).set("ymax",ymax+"[um]");try{m.component("comp1").selection(name).set("condition","inside");}catch(Throwable e){}}
    void union(String name,int dim,String[] inputs){m.component("comp1").selection().create(name,"Union");m.component("comp1").selection(name).set("entitydim",dim);m.component("comp1").selection(name).set("input",inputs);} 
    void p4(){P("[4] Materials"); mat("mat_Al","sel_al","rho_Al","E_Al","nu_Al"); mat("mat_Dia","sel_dia","rho_Dia","E_Dia","nu_Dia"); mat("mat_Tool","sel_tools","rho_tool","E_tool","nu_tool"); mat("mat_Wall","sel_walls","rho_wall","E_wall","nu_wall");}
    void mat(String tag,String sel,String rho,String E,String nu){m.component("comp1").material().create(tag,"Common");m.component("comp1").material(tag).selection().named(sel);m.component("comp1").material(tag).propertyGroup("def").set("density",rho);m.component("comp1").material(tag).propertyGroup("def").set("youngsmodulus",E);m.component("comp1").material(tag).propertyGroup("def").set("poissonsratio",nu);} 
    void p5(){P("[5] Solid"); m.component("comp1").physics().create("solid","SolidMechanics","geom1"); m.component("comp1").physics("solid").create("fix_bottom","Fixed",2); m.component("comp1").physics("solid").feature("fix_bottom").selection().named("sel_lower_punch"); m.component("comp1").physics("solid").create("fix_left","Fixed",2);m.component("comp1").physics("solid").feature("fix_left").selection().named("sel_left_wall");m.component("comp1").physics("solid").create("fix_right","Fixed",2);m.component("comp1").physics("solid").feature("fix_right").selection().named("sel_right_wall"); m.component("comp1").physics("solid").create("disp_top","PrescribedDisplacement",1); m.component("comp1").physics("solid").feature("disp_top").selection().named("bnd_upper_inner"); try{m.component("comp1").physics("solid").feature("disp_top").set("PrescribedDisplacement",new String[]{"0","-uTop","0"});}catch(Throwable e){m.component("comp1").physics("solid").feature("disp_top").set("U0",new String[]{"0","-uTop","0"});} addAlPlastic(); }
    void addAlPlastic(){try{Object p=m.component("comp1").physics("solid").feature("lemm1").feature().create("plas_al","Plasticity",2);m.component("comp1").physics("solid").feature("lemm1").feature("plas_al").selection().named("sel_al"); setObj(p,"YieldFunction","mises");setObj(p,"IsotropicHardeningModel","LinearIsotropicHardening");setObj(p,"ys_mat","userdef");setArr(p,"ys",new String[]{"sigy_Al","sigy_Al","sigy_Al","0","0","0"});setObj(p,"sigmags_mat","userdef");setObj(p,"sigmags","sigy_Al/sqrt(3)");setObj(p,"sigmagf","sigy_Al");setObj(p,"Et_mat","userdef");setObj(p,"Et","500[MPa]");}catch(Throwable e){P("  Plasticity FAIL: "+msg(e));}}
    void setObj(Object o,String k,String v){try{o.getClass().getMethod("set",String.class,String.class).invoke(o,k,v);P("  "+k+" OK");}catch(Throwable e){P("  "+k+" FAIL: "+msg(e));}} void setArr(Object o,String k,String[] v){try{o.getClass().getMethod("set",String.class,String[].class).invoke(o,k,(Object)v);P("  "+k+" OK");}catch(Throwable e){P("  "+k+" FAIL: "+msg(e));}}
    void p6(){P("[6] Contact");try{m.component("comp1").pair().create("gcp1","GeneralContact","geom1");}catch(Throwable e){}try{m.component("comp1").physics("solid").feature("dcont1").set("pairs",new String[]{});}catch(Throwable e){}try{m.component("comp1").physics("solid").feature("dgcnt1").active(true);m.component("comp1").physics("solid").feature("dgcnt1").set("pairs",new String[]{"gcp1"});m.component("comp1").physics("solid").feature("dgcnt1").feature("cmod1").set("penaltyFactorMultiplier","automatic");m.component("comp1").physics("solid").feature("dgcnt1").feature("cmod1").create("fric1","Friction",1);m.component("comp1").physics("solid").feature("dgcnt1").feature("cmod1").feature("fric1").set("FrictionModel","Coulomb");m.component("comp1").physics("solid").feature("dgcnt1").feature("cmod1").feature("fric1").set("mu_fric","mu_contact");}catch(Throwable e){P("  contact FAIL: "+msg(e));}}
    void p7(){P("[7] Mesh");m.component("comp1").mesh().create("mesh1");m.component("comp1").mesh("mesh1").create("ftri1","FreeTri");m.component("comp1").mesh("mesh1").feature("size").set("hmax","8[um]");m.component("comp1").mesh("mesh1").feature("size").set("hmin","0.7[um]");}
    void p8(){P("[8] Solver");m.study().create("std1");m.study("std1").create("stat","Stationary");try{m.study("std1").feature("stat").set("geometricNonlinearity","on");}catch(Throwable e){}m.sol().create("sol1");m.sol("sol1").study("std1");m.sol("sol1").attach("std1");m.sol("sol1").feature().create("st1","StudyStep");m.sol("sol1").feature().create("v1","Variables");m.sol("sol1").feature().create("s1","Stationary");m.sol("sol1").feature("s1").feature().create("p1","Parametric");m.sol("sol1").feature("s1").feature("p1").set("pname",new String[]{"uTop"});m.sol("sol1").feature("s1").feature("p1").set("plistarr",new String[]{"0 0.2 0.5 1 2 3 5 8 12 16 20 25 30"});m.sol("sol1").feature("s1").feature("p1").set("punit",new String[]{"um"});m.sol("sol1").feature("s1").feature().create("fc1","FullyCoupled");m.sol("sol1").feature("s1").feature().create("d1","Direct");m.sol("sol1").feature("s1").feature("d1").set("linsolver","pardiso");m.sol("sol1").feature("s1").feature("fc1").set("linsolver","d1");m.sol("sol1").feature("s1").feature("fc1").set("maxiter",300);m.sol("sol1").feature("s1").feature("fc1").set("dampfactor",0.05);m.sol("sol1").feature("s1").feature("fc1").set("ntolfact",10.0);m.sol("sol1").feature("s1").feature("fc1").set("dtech","auto");}
    void runSolve(){P("[RUN]");try{m.sol("sol1").runAll();P("[RUN] OK");}catch(Throwable e){P("[RUN FAIL] "+msg(e));}}
    void p9(){P("[9] Results");try{m.component("comp1").cpl().create("intop_top","Integration");m.component("comp1").cpl("intop_top").selection().named("bnd_upper_inner");m.result().numerical().create("ev_peq","EvalGlobal");m.result().numerical("ev_peq").setIndex("expr","-intop_top(solid.RFy)/W_geom",0);}catch(Throwable e){P("  peq result FAIL: "+msg(e));}try{m.result().create("pg_epe","PlotGroup2D");m.result("pg_epe").create("surf1","Surface");m.result("pg_epe").feature("surf1").set("expr","solid.epe");}catch(Throwable e){}}
    void save(){try{m.save(outPath);P("[SAVE OK] "+outPath);}catch(Throwable e){P("[SAVE FAIL] "+msg(e));}}
    static String msg(Throwable e){Throwable c=e.getCause();String m=(c!=null?c.getMessage():e.getMessage());return m==null?"null":m.substring(0,Math.min(160,m.length())).replace('\n',' ');} 
}
