from __future__ import annotations

import argparse
import math
from pathlib import Path


PARTICLE_COUNT = 2000
PARTICLE_DIAMETER_UM = 30.0
PARTICLE_RADIUS_UM = PARTICLE_DIAMETER_UM / 2.0
DIE_DIAMETER_UM = 450.0
INITIAL_HEIGHT_UM = 900.0
TARGET_RELATIVE_DENSITIES = (0.30, 0.38, 0.46, 0.54)
DT_SECONDS = 2.0e-7
TOP_VEL_CM_S = 2.0
SETTLE_STEPS = 20000
FINAL_SETTLE_STEPS = 40000

# Literature/material-table values for dense alpha alumina are kept in metadata.
ALUMINA_TRUE_DENSITY_G_CM3 = 3.95
ALUMINA_TRUE_YOUNG_GPA = 365.0
ALUMINA_TRUE_POISSON = 0.24
STEEL_TOOL_YOUNG_GPA = 200.0
STEEL_TOOL_POISSON = 0.30

# Reduced DEM stiffness keeps a 2000-particle CI run tractable. The force-density
# curve is therefore a computational screening result, not a calibrated press law.
ALUMINA_DEM_YOUNG_GPA = 0.50
TOOL_DEM_YOUNG_GPA = 5.0
DIE_DEM_YOUNG_GPA = 5.0

SEED_TABLE = [
    {"template": 15485863, "distribution": 15485867, "insert": 32452843},
    {"template": 32452867, "distribution": 49979693, "insert": 67867967},
    {"template": 49979687, "distribution": 67867979, "insert": 86028121},
    {"template": 67867967, "distribution": 86028157, "insert": 15485867},
    {"template": 86028121, "distribution": 32452843, "insert": 49979693},
]


def sphere_volume_cm3(radius_um: float) -> float:
    r_cm = radius_um * 1.0e-4
    return 4.0 / 3.0 * math.pi * r_cm**3


def die_area_cm2(diameter_um: float) -> float:
    r_cm = diameter_um * 0.5 * 1.0e-4
    return math.pi * r_cm**2


def particle_solid_volume_cm3() -> float:
    return PARTICLE_COUNT * sphere_volume_cm3(PARTICLE_RADIUS_UM)


def height_for_density_um(relative_density: float) -> float:
    return particle_solid_volume_cm3() / (die_area_cm2(DIE_DIAMETER_UM) * relative_density) * 1.0e4


def gpa_to_cgs(value_gpa: float) -> str:
    return f"{value_gpa * 1.0e10:.9g}"


def seed_values(seed_index: int) -> dict[str, int]:
    return SEED_TABLE[seed_index % len(SEED_TABLE)]


def stage_rows() -> list[dict[str, float | str]]:
    rows = []
    previous_displacement_um = 0.0
    for i, rho in enumerate(TARGET_RELATIVE_DENSITIES, start=1):
        height_um = height_for_density_um(rho)
        displacement_um = INITIAL_HEIGHT_UM - height_um
        if displacement_um <= previous_displacement_um:
            raise SystemExit(f"[FAIL] non-monotonic displacement at rho={rho}")
        incremental_um = displacement_um - previous_displacement_um
        run_steps = max(1, int(round(incremental_um * 1.0e-4 / (TOP_VEL_CM_S * DT_SECONDS))))
        rows.append(
            {
                "stage": f"stage{i}_rho{int(round(rho * 100)):03d}",
                "rho": rho,
                "height_um": height_um,
                "displacement_um": displacement_um,
                "incremental_um": incremental_um,
                "run_steps": run_steps,
            }
        )
        previous_displacement_um = displacement_um
    return rows


def render(seed: int) -> str:
    seeds = seed_values(seed)
    radius_cm = PARTICLE_RADIUS_UM * 1.0e-4
    die_radius_cm = DIE_DIAMETER_UM * 0.5 * 1.0e-4
    initial_height_cm = INITIAL_HEIGHT_UM * 1.0e-4
    insert_zlo = radius_cm * 1.05
    insert_zhi = initial_height_cm - radius_cm * 1.20
    insert_radius_cm = die_radius_cm - radius_cm * 1.10
    solid_vol = particle_solid_volume_cm3()
    area = die_area_cm2(DIE_DIAMETER_UM)

    lines = [
        "# 3D alumina powder uniaxial die compaction",
        "# Units: cgs (cm, g, s). Generated by python/render_alumina3d_deck.py",
        "atom_style      granular",
        "atom_modify     map array",
        "boundary        f f f",
        "newton          off",
        "communicate     single vel yes",
        "units           cgs",
        "",
        f"variable        dieRadiusCm equal {die_radius_cm:.12g}",
        f"variable        dieAreaCm2 equal {area:.12g}",
        f"variable        solidVolumeCm3 equal {solid_vol:.12g}",
        f"variable        topVel equal {TOP_VEL_CM_S:.12g}",
        f"variable        dt equal {DT_SECONDS:.12g}",
        "",
        f"region          simreg cylinder z 0.0 0.0 {die_radius_cm * 1.15:.12g} -0.001 {initial_height_cm * 1.08:.12g} units box",
        "create_box      3 simreg",
        "neighbor        0.0006 bin",
        "neigh_modify    delay 0",
        "timestep        ${dt}",
        "",
        "# type 1 = alumina particle, type 2 = top punch, type 3 = die/bottom wall.",
        "hard_particles  yes",
        "fix             mprop all property/global youngsModulus peratomtype "
        f"{gpa_to_cgs(ALUMINA_DEM_YOUNG_GPA)} {gpa_to_cgs(TOOL_DEM_YOUNG_GPA)} {gpa_to_cgs(DIE_DEM_YOUNG_GPA)}",
        f"fix             pprop all property/global poissonsRatio peratomtype {ALUMINA_TRUE_POISSON:.6g} {STEEL_TOOL_POISSON:.6g} {STEEL_TOOL_POISSON:.6g}",
        "fix             cor all property/global coefficientRestitution peratomtypepair 3 &",
        "                0.35 0.25 0.25 &",
        "                0.25 0.20 0.20 &",
        "                0.25 0.20 0.20",
        "fix             cof all property/global coefficientFriction peratomtypepair 3 &",
        "                0.45 0.35 0.35 &",
        "                0.35 0.20 0.20 &",
        "                0.35 0.20 0.20",
        "pair_style      gran model hertz tangential history",
        "pair_coeff      * *",
        "",
        "fix             grav all gravity 981 vector 0.0 0.0 -1.0",
        "fix             integr all nve/sphere",
        "fix             side all mesh/surface/stress file meshes/DieCylinder.stl type 3 scale 1.0 stress on",
        "fix             bottom all mesh/surface/stress file meshes/BottomPlate.stl type 3 scale 1.0 stress on",
        "fix             top all mesh/surface/stress file meshes/TopPunch.stl type 2 scale 1.0 stress on",
        "fix             walls all wall/gran model hertz tangential history mesh n_meshes 3 meshes side bottom top",
        "",
        "variable        topForceZDyn equal f_top[3]",
        "variable        topForceAbsDyn equal abs(f_top[3])",
        "variable        bottomForceZDyn equal f_bottom[3]",
        "variable        bottomForceAbsDyn equal abs(f_bottom[3])",
        "variable        sideForceAbsDyn equal sqrt(f_side[1]*f_side[1]+f_side[2]*f_side[2]+f_side[3]*f_side[3])",
        "variable        pressureMPa equal v_topForceAbsDyn/v_dieAreaCm2*1.0e-7",
        "variable        bottomPressureMPa equal v_bottomForceAbsDyn/v_dieAreaCm2*1.0e-7",
        "",
        f"fix             ptsAlumina all particletemplate/sphere {seeds['template']} atom_type 1 density constant {ALUMINA_TRUE_DENSITY_G_CM3:.6g} radius constant {radius_cm:.12g}",
        f"fix             pddAlumina all particledistribution/discrete/numberbased {seeds['distribution']} 1 ptsAlumina 1.0",
        f"region          particles_in_region cylinder z 0.0 0.0 {insert_radius_cm:.12g} {insert_zlo:.12g} {insert_zhi:.12g} units box",
        f"fix             insAlumina all insert/pack seed {seeds['insert']} distributiontemplate pddAlumina maxattempt 500000 insert_every once overlapcheck yes all_in yes particles_in_region {PARTICLE_COUNT} region particles_in_region ntry_mc 500000",
        "run             1",
        "unfix           insAlumina",
        "",
        "thermo_style    custom step atoms ke f_top[3] v_pressureMPa",
        "thermo          2000",
        "dump            trace all custom 10000 DEM/alumina3d_trace_*.dump id type x y z vx vy vz radius",
        "",
        'print           "stage_id,target_relative_density,current_height_um,top_displacement_um,top_force_z_dyne,top_force_abs_dyne,pressure_mpa,bottom_force_z_dyne,bottom_pressure_mpa,side_force_abs_dyne" file DEM/alumina3d_pressure_density_raw.csv screen no',
        'print           "parameter,value,unit" file DEM/model_parameters.csv screen no',
        f'print           "material,Al2O3,text" append DEM/model_parameters.csv screen no',
        f'print           "particle_count,{PARTICLE_COUNT},1" append DEM/model_parameters.csv screen no',
        f'print           "particle_diameter_um,{PARTICLE_DIAMETER_UM:.9g},um" append DEM/model_parameters.csv screen no',
        f'print           "die_diameter_um,{DIE_DIAMETER_UM:.9g},um" append DEM/model_parameters.csv screen no',
        f'print           "initial_height_um,{INITIAL_HEIGHT_UM:.9g},um" append DEM/model_parameters.csv screen no',
        f'print           "solid_volume_cm3,{solid_vol:.9g},cm3" append DEM/model_parameters.csv screen no',
        f'print           "true_density_g_cm3,{ALUMINA_TRUE_DENSITY_G_CM3:.9g},g/cm3" append DEM/model_parameters.csv screen no',
        f'print           "true_young_modulus_gpa,{ALUMINA_TRUE_YOUNG_GPA:.9g},GPa" append DEM/model_parameters.csv screen no',
        f'print           "true_poisson_ratio,{ALUMINA_TRUE_POISSON:.9g},1" append DEM/model_parameters.csv screen no',
        f'print           "dem_young_modulus_gpa,{ALUMINA_DEM_YOUNG_GPA:.9g},GPa" append DEM/model_parameters.csv screen no',
        f'print           "DEM_seed_index,{seed},1" append DEM/model_parameters.csv screen no',
        f'print           "DEM_seed_table_slot,{seed % len(SEED_TABLE)},1" append DEM/model_parameters.csv screen no',
        f'print           "DEM_template_seed,{seeds["template"]},1" append DEM/model_parameters.csv screen no',
        f'print           "DEM_distribution_seed,{seeds["distribution"]},1" append DEM/model_parameters.csv screen no',
        f'print           "DEM_insert_seed,{seeds["insert"]},1" append DEM/model_parameters.csv screen no',
        f'print           "particle_particle_friction,0.45,1" append DEM/model_parameters.csv screen no',
        f'print           "particle_wall_friction,0.35,1" append DEM/model_parameters.csv screen no',
        f'print           "coefficient_restitution_particle_particle,0.35,1" append DEM/model_parameters.csv screen no',
        f'print           "source_note,Alumina properties from engineering ceramic tables; DEM stiffness reduced for CI-scale explicit timestep,text" append DEM/model_parameters.csv screen no',
        "",
        f"run             {SETTLE_STEPS}",
    ]

    stages = stage_rows()
    for idx, row in enumerate(stages):
        lines.extend(
            [
                "",
                f"# {row['stage']}: compact to relative density {row['rho']:.3f}",
                "fix             topMove all move/mesh mesh top linear 0.0 0.0 -${topVel}",
                f"run             {row['run_steps']}",
                "unfix           topMove",
                f"run             {FINAL_SETTLE_STEPS if idx == len(stages) - 1 else SETTLE_STEPS}",
                (
                    f'print           "{row["stage"]},{row["rho"]:.6g},{row["height_um"]:.9g},'
                    f'{row["displacement_um"]:.9g},${{topForceZDyn}},${{topForceAbsDyn}},${{pressureMPa}},'
                    '${bottomForceZDyn},${bottomPressureMPa},${sideForceAbsDyn}" append DEM/alumina3d_pressure_density_raw.csv screen no'
                ),
                f"dump            {row['stage']} all custom 1 DEM/{row['stage']}_*.dump id type x y z vx vy vz radius",
                "run             0",
                f"undump          {row['stage']}",
                f"write_restart   DEM/{row['stage']}.restart",
            ]
        )

    lines.extend(["", "undump          trace", ""])
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--output", default="liggghts/alumina3d/in.alumina3d_compaction.rendered.liggghts")
    ap.add_argument("--seed", type=int, default=0, help="Deterministic seed-table index; modulo the built-in prime seed table.")
    args = ap.parse_args()

    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render(args.seed), encoding="utf-8", newline="\n")
    print(f"[OK] wrote {out}")
    seeds = seed_values(args.seed)
    print(f"[PARAM] particles={PARTICLE_COUNT} diameter_um={PARTICLE_DIAMETER_UM} die_diameter_um={DIE_DIAMETER_UM} initial_height_um={INITIAL_HEIGHT_UM}")
    print(f"[PARAM] seed_index={args.seed} template={seeds['template']} distribution={seeds['distribution']} insert={seeds['insert']}")
    for row in stage_rows():
        print(
            f"[STAGE] {row['stage']} rho={row['rho']:.3f} "
            f"height_um={row['height_um']:.3f} displacement_um={row['displacement_um']:.3f} "
            f"run_steps={row['run_steps']}"
        )


if __name__ == "__main__":
    main()
